### ISSUE TITLE
Questionable answer? X|7/|9-|X|-8|8/|-6|X|X|X||81

### ISSUE THREAD

**Issue by heyulinxp** [recruiting-system/2017-04-28-03-33-58-1493350438#2]
X|7/|9-|X|-8|8/|-6|X|X|X||81
I get the answer 181, but the given answer is 167?
The ball point list is 
10
7
3 
9
10 
8
8 
2
6
10
10
10
8
1

The accumulation list is 
20
39
48
74
82
98
104
134
162
181

Where is my mistake? Or the given answer is wrong?

**Comment by BubbleM** [comment]
@heyulinxp  你不能直接把miss的情况忽略掉 miss是丢了一次球不过一个都没中  第四局的分数应该是18（因为第四局第一次机会就全中 所以分数为10+接下来的两次机会（第五局中第一次miss和第二次8）即10+0+8）而你忽略了第五局的第一次机会miss（10+8+8=26 错误的加上了第6局的第一次机会8）  导致错误开始   正确的每局得分情况应该是20，19，9，18，8，10，6，30，28，19

**Comment by heyulinxp** [comment]
喔喔懂了，非常感谢~
